-- SDGW 1914-1919 Reference Data
-- Seed tables for regiment names, theatre of war groups, region places, and place keywords.
-- These tables are the source of truth — edit them directly in the database to maintain.

-- ============================================================
-- Regiment Names
-- ============================================================
CREATE TABLE IF NOT EXISTS ref_regiment_names (
    regiment_id INTEGER PRIMARY KEY,
    name        TEXT NOT NULL
);

INSERT OR IGNORE INTO ref_regiment_names (regiment_id, name) VALUES
(1, 'Cavalry'),
(3, 'The Royal Fusiliers (City of London Regiment)'),
(5, 'The King''s (Liverpool Regiment)'),
(7, 'The Norfolk Regiment'),
(9, 'The Lincolnshire Regiment'),
(11, 'The Devonshire Regiment'),
(13, 'The Suffolk Regiment'),
(15, 'The Prince Albert''s (Somerset Light Infantry)'),
(17, 'The Prince of Wales''s (West Yorkshire Regiment)'),
(18, 'The East Yorkshire Regiment'),
(19, 'Unknown Regiment'),
(20, 'The King''s Shropshire Light Infantry'),
(21, 'Cyclist Battalions'),
(22, 'Unknown Regiment'),
(24, 'Territorial Force'),
(26, 'The Bedfordshire Regiment'),
(28, 'The Leicestershire Regiment'),
(30, 'The Lancashire Fusiliers'),
(32, 'The East Lancashire Regiment'),
(34, 'The South Lancashire Regiment'),
(36, 'The Duke of Wellington''s (West Riding Regiment)'),
(38, 'The Border Regiment'),
(40, 'The Royal Sussex Regiment'),
(42, 'The Hampshire Regiment'),
(44, 'The South Staffordshire Regiment'),
(46, 'The Dorsetshire Regiment'),
(48, 'The Prince of Wales''s Volunteers (South Lancashire)'),
(50, 'The Welsh Regiment'),
(52, 'The Black Watch (Royal Highlanders)'),
(54, 'The Oxfordshire and Buckinghamshire Light Infantry'),
(56, 'The Essex Regiment'),
(58, 'The Sherwood Foresters (Nottinghamshire & Derbyshire)'),
(60, 'The Loyal North Lancashire Regiment'),
(62, 'The Northamptonshire Regiment'),
(64, 'Princess Charlotte of Wales''s (Royal Berkshire Regiment)'),
(66, 'The Queen''s Own (Royal West Kent Regiment)'),
(68, 'The King''s Own Yorkshire Light Infantry'),
(70, 'The King''s (Shropshire Light Infantry)'),
(72, 'The Duke of Cambridge''s Own (Middlesex Regiment)'),
(74, 'The King''s Royal Rifle Corps'),
(76, 'The Duke of Edinburgh''s (Wiltshire Regiment)'),
(78, 'The Manchester Regiment'),
(80, 'The Prince of Wales''s (North Staffordshire Regiment)'),
(82, 'The York and Lancaster Regiment'),
(84, 'The Durham Light Infantry'),
(86, 'The Highland Light Infantry'),
(88, 'Seaforth Highlanders (Ross-shire Buffs, Duke of Albany''s)'),
(90, 'The Gordon Highlanders'),
(92, 'The Queen''s Own Cameron Highlanders'),
(94, 'The Royal Irish Rifles'),
(96, 'Princess Victoria''s (Royal Irish Fusiliers)'),
(98, 'The Connaught Rangers'),
(100, 'Princess Louise''s (Argyll & Sutherland Highlanders)'),
(102, 'The Prince of Wales''s Leinster Regiment'),
(104, 'The Royal Munster Fusiliers'),
(106, 'The Royal Dublin Fusiliers'),
(108, 'The Rifle Brigade (Prince Consort''s Own)'),
(110, 'Royal Artillery'),
(112, 'Royal Engineers'),
(114, 'Royal Army Medical Corps'),
(116, 'Army Service Corps'),
(118, 'Machine Gun Corps'),
(120, 'Tank Corps'),
(122, 'Royal Army Ordnance Corps'),
(124, 'Army Veterinary Corps'),
(126, 'Military Police'),
(128, 'Royal Flying Corps / Royal Air Force'),
(130, 'Labour Corps'),
(132, 'Guards Division'),
(134, 'The Cameronians (Scottish Rifles)'),
(136, 'The Royal Inniskilling Fusiliers'),
(138, 'The Gloucestershire Regiment'),
(140, 'The Worcestershire Regiment'),
(142, 'The East Surrey Regiment'),
(144, 'The Duke of Cornwall''s Light Infantry'),
(146, 'The West Yorkshire Regiment'),
(148, 'The Royal Scots Fusiliers'),
(150, 'The York and Lancaster Regiment'),
(152, 'The Royal West Surrey Regiment (The Queen''s)'),
(154, 'The Royal Warwickshire Regiment'),
(156, 'The Royal Scots (Lothian Regiment)'),
(158, 'The Middlesex Regiment'),
(160, 'The Rifle Brigade'),
(162, 'Training Reserve / Motor / Misc'),
(164, 'Unknown / Unclassified'),
(166, 'London Regiment'),
(168, 'The Cheshire Regiment'),
(170, 'Unknown / Unclassified'),
(171, 'Unknown / Unclassified'),
(173, 'Unknown / Unclassified'),
(174, 'Unknown / Unclassified'),
(175, 'Unknown / Unclassified'),
(176, 'Channel Islands Militia'),
(177, 'Military Foot / Mounted Police'),
(178, 'Unknown / Unclassified'),
(179, 'Unknown / Unclassified'),
(180, 'Unknown / Unclassified'),
(181, 'Unknown / Unclassified'),
(183, 'Unknown / Unclassified'),
(184, 'The South Wales Borderers'),
(186, 'The Royal Welsh Fusiliers');

-- ============================================================
-- Theatre of War Groups
-- ============================================================
CREATE TABLE IF NOT EXISTS ref_theatre_groups (
    location      TEXT PRIMARY KEY,
    theatre_group TEXT NOT NULL
);

INSERT OR IGNORE INTO ref_theatre_groups (location, theatre_group) VALUES
('France & Flanders', 'Western Front'),
('British Expeditionary Force', 'Western Front'),
('British Expeditionary Force (Italy)', 'Western Front'),
('Belgium', 'Western Front'),
('Antwerp', 'Western Front'),
('Gallipoli', 'Gallipoli & Dardanelles'),
('Dardanelles', 'Gallipoli & Dardanelles'),
('Sulva Bay', 'Gallipoli & Dardanelles'),
('Suvla', 'Gallipoli & Dardanelles'),
('Imbros', 'Gallipoli & Dardanelles'),
('Lemnos', 'Gallipoli & Dardanelles'),
('Mudros', 'Gallipoli & Dardanelles'),
('West Mudros', 'Gallipoli & Dardanelles'),
('Mesopotamia', 'Mesopotamia & Persian Gulf'),
('Mesopotamian Expeditionary Force', 'Mesopotamia & Persian Gulf'),
('Persian Gulf', 'Mesopotamia & Persian Gulf'),
('Baghdad', 'Mesopotamia & Persian Gulf'),
('Basra', 'Mesopotamia & Persian Gulf'),
('Busra - sic', 'Mesopotamia & Persian Gulf'),
('East Persia', 'Mesopotamia & Persian Gulf'),
('Persia', 'Mesopotamia & Persian Gulf'),
('Egypt', 'Egypt & Palestine'),
('Palestine', 'Egypt & Palestine'),
('E.E.F.', 'Egypt & Palestine'),
('El Arish', 'Egypt & Palestine'),
('Gaza', 'Egypt & Palestine'),
('Kantara', 'Egypt & Palestine'),
('Cairo', 'Egypt & Palestine'),
('Port Said', 'Egypt & Palestine'),
('Port Suez', 'Egypt & Palestine'),
('Suez', 'Egypt & Palestine'),
('Abbassia', 'Egypt & Palestine'),
('Aboukir', 'Egypt & Palestine'),
('Salonika', 'Salonika & Balkans'),
('Balkans', 'Salonika & Balkans'),
('Palkans - sic', 'Salonika & Balkans'),
('Greek Macedonia', 'Salonika & Balkans'),
('Greece', 'Salonika & Balkans'),
('Nigrita, Greece', 'Salonika & Balkans'),
('Serbia', 'Salonika & Balkans'),
('Macedonia', 'Salonika & Balkans'),
('Bulgaria', 'Salonika & Balkans'),
('Africa', 'Africa'),
('African Expeditionary Force', 'Africa'),
('British East Africa', 'Africa'),
('East Africa', 'Africa'),
('German East Africa', 'Africa'),
('Central Africa', 'Africa'),
('Cameroons', 'Africa'),
('West Africa', 'Africa'),
('West African Frontier Force', 'Africa'),
('West Coast of Africa', 'Africa'),
('Uakern, W. Africa', 'Africa'),
('Nigeria', 'Africa'),
('Sierra Leone', 'Africa'),
('Kaduna Africa', 'Africa'),
('Mahiwa, East africa', 'Africa'),
('Cape Town, South Africa', 'Africa'),
('South Africa', 'Africa'),
('Durban', 'Africa'),
('Khartoum', 'Africa'),
('Eritrea', 'Africa'),
('Portuguese East Africa', 'Africa'),
('Port Sudan', 'Africa'),
('India', 'India & Burma'),
('I.E.F.', 'India & Burma'),
('Bombay', 'India & Burma'),
('Colaba, India', 'India & Burma'),
('Jhansi', 'India & Burma'),
('Lucknow', 'India & Burma'),
('Madras', 'India & Burma'),
('Meerut, India', 'India & Burma'),
('N.W.F.', 'India & Burma'),
('Nowshera', 'India & Burma'),
('Poona, India', 'India & Burma'),
('Quetta', 'India & Burma'),
('Rangoon', 'India & Burma'),
('Kotuh? Burmah', 'India & Burma'),
('Italy', 'Italy'),
('Taranto, Italy', 'Italy'),
('At Sea', 'At Sea'),
('Black Sea', 'At Sea'),
('Home', 'Home'),
('At Home', 'Home'),
('Home Commd.', 'Home'),
('Home (Dublin)', 'Home'),
('Aldershot', 'Home'),
('Hull', 'Home'),
('Russia', 'Russia'),
('Russian Poland', 'Russia'),
('North Russia', 'Russia'),
('North Russian Expeditionary Force', 'Russia'),
('South Russia', 'Russia'),
('Archangel', 'Russia'),
('Siberia', 'Russia'),
('Poland', 'Russia'),
('China', 'Far East'),
('North China', 'Far East'),
('Hong Kong', 'Far East'),
('Singapore', 'Far East'),
('Singapore, Straits Settlements', 'Far East'),
('Ceylon', 'Far East'),
('Andaman Islands', 'Far East'),
('Mauritius', 'Far East'),
('Aden', 'Other'),
('Arabia', 'Other'),
('Asia Minor', 'Other'),
('Constantinople', 'Other'),
('Cyprus', 'Other'),
('Damascus', 'Other'),
('Tarsus', 'Other'),
('Turkey', 'Other'),
('Turkey in Asia', 'Other'),
('M.E.F.', 'Other'),
('Mediterranean', 'Other'),
('Malta', 'Other'),
('Gibraltar', 'Other'),
('America', 'Other'),
('Continent of America', 'Other'),
('U.S.A.', 'Other'),
('Halifax, Nova Scotia', 'Other'),
('Canada', 'Other'),
('Nova Scotia', 'Other'),
('Montreal, Canada', 'Other'),
('Australia', 'Other'),
('Bermuda', 'Other'),
('Jamaica', 'Other'),
('Copenhagen', 'Other'),
('Holland', 'Other'),
('Germany', 'Other'),
('Austria', 'Other'),
('Gefangenlager', 'Other'),
('Munster', 'Other'),
('Switzerland', 'Other'),
('Baghtche', 'Other'),
('Baku', 'Other'),
('Chalkadra', 'Other'),
('Poli', 'Other'),
('Alexandria', 'Other');

-- ============================================================
-- Region Places (counties and cities for birth/enlistment classification)
-- ============================================================
CREATE TABLE IF NOT EXISTS ref_region_places (
    place_name TEXT NOT NULL,
    country    TEXT NOT NULL,
    type       TEXT NOT NULL CHECK(type IN ('county', 'city')),
    PRIMARY KEY (place_name, country, type)
);

-- Scotland counties
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('ABERDEEN', 'Scotland', 'county'),
('ABERDEENSHIRE', 'Scotland', 'county'),
('ANGUS', 'Scotland', 'county'),
('ARGYLL', 'Scotland', 'county'),
('ARGYLLSHIRE', 'Scotland', 'county'),
('AYR', 'Scotland', 'county'),
('AYRSHIRE', 'Scotland', 'county'),
('BANFF', 'Scotland', 'county'),
('BANFFSHIRE', 'Scotland', 'county'),
('BERWICK', 'Scotland', 'county'),
('BERWICKSHIRE', 'Scotland', 'county'),
('BUTE', 'Scotland', 'county'),
('CAITHNESS', 'Scotland', 'county'),
('CLACKMANNAN', 'Scotland', 'county'),
('CLACKMANNANSHIRE', 'Scotland', 'county'),
('DUMBARTON', 'Scotland', 'county'),
('DUMBARTONSHIRE', 'Scotland', 'county'),
('DUMFRIES', 'Scotland', 'county'),
('DUMFRIESSHIRE', 'Scotland', 'county'),
('DUNDEE', 'Scotland', 'county'),
('DUNBARTONSHIRE', 'Scotland', 'county'),
('EAST LOTHIAN', 'Scotland', 'county'),
('EDINBURGH', 'Scotland', 'county'),
('ELGIN', 'Scotland', 'county'),
('FIFE', 'Scotland', 'county'),
('FORFAR', 'Scotland', 'county'),
('FORFARSHIRE', 'Scotland', 'county'),
('GLASGOW', 'Scotland', 'county'),
('HADDINGTON', 'Scotland', 'county'),
('HADDINGTONSHIRE', 'Scotland', 'county'),
('INVERNESS', 'Scotland', 'county'),
('INVERNESS-SHIRE', 'Scotland', 'county'),
('KINCARDINE', 'Scotland', 'county'),
('KINCARDINESHIRE', 'Scotland', 'county'),
('KINROSS', 'Scotland', 'county'),
('KINROSS-SHIRE', 'Scotland', 'county'),
('KIRKCUDBRIGHT', 'Scotland', 'county'),
('KIRKCUDBRIGHTSHIRE', 'Scotland', 'county'),
('LANARK', 'Scotland', 'county'),
('LANARKSHIRE', 'Scotland', 'county'),
('LINLITHGOW', 'Scotland', 'county'),
('LINLITHGOWSHIRE', 'Scotland', 'county'),
('MIDLOTHIAN', 'Scotland', 'county'),
('MORAY', 'Scotland', 'county'),
('NAIRN', 'Scotland', 'county'),
('NAIRNSHIRE', 'Scotland', 'county'),
('ORKNEY', 'Scotland', 'county'),
('PEEBLES', 'Scotland', 'county'),
('PEEBLESSHIRE', 'Scotland', 'county'),
('PERTH', 'Scotland', 'county'),
('PERTHSHIRE', 'Scotland', 'county'),
('RENFREW', 'Scotland', 'county'),
('RENFREWSHIRE', 'Scotland', 'county'),
('ROSS', 'Scotland', 'county'),
('ROSS-SHIRE', 'Scotland', 'county'),
('ROXBURGH', 'Scotland', 'county'),
('ROXBURGHSHIRE', 'Scotland', 'county'),
('SELKIRK', 'Scotland', 'county'),
('SELKIRKSHIRE', 'Scotland', 'county'),
('SHETLAND', 'Scotland', 'county'),
('STIRLING', 'Scotland', 'county'),
('STIRLINGSHIRE', 'Scotland', 'county'),
('SUTHERLAND', 'Scotland', 'county'),
('WEST LOTHIAN', 'Scotland', 'county'),
('WIGTOWN', 'Scotland', 'county'),
('WIGTOWNSHIRE', 'Scotland', 'county');

-- Scotland cities
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('ABERDEEN', 'Scotland', 'city'),
('DUNDEE', 'Scotland', 'city'),
('EDINBURGH', 'Scotland', 'city'),
('GLASGOW', 'Scotland', 'city'),
('GREENOCK', 'Scotland', 'city'),
('PAISLEY', 'Scotland', 'city'),
('PERTH', 'Scotland', 'city'),
('STIRLING', 'Scotland', 'city'),
('INVERNESS', 'Scotland', 'city'),
('FALKIRK', 'Scotland', 'city'),
('KILMARNOCK', 'Scotland', 'city'),
('MOTHERWELL', 'Scotland', 'city'),
('COATBRIDGE', 'Scotland', 'city'),
('HAMILTON', 'Scotland', 'city'),
('KIRKCALDY', 'Scotland', 'city'),
('DUNFERMLINE', 'Scotland', 'city'),
('AYR', 'Scotland', 'city'),
('DUMFRIES', 'Scotland', 'city'),
('ARBROATH', 'Scotland', 'city'),
('ALLOA', 'Scotland', 'city'),
('LEITH', 'Scotland', 'city'),
('GALASHIELS', 'Scotland', 'city'),
('HAWICK', 'Scotland', 'city'),
('MUSSELBURGH', 'Scotland', 'city');

-- Wales counties
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('ANGLESEY', 'Wales', 'county'),
('BRECON', 'Wales', 'county'),
('BRECKNOCKSHIRE', 'Wales', 'county'),
('BRECONSHIRE', 'Wales', 'county'),
('CAERNARVON', 'Wales', 'county'),
('CAERNARVONSHIRE', 'Wales', 'county'),
('CARDIGAN', 'Wales', 'county'),
('CARDIGANSHIRE', 'Wales', 'county'),
('CARMARTHEN', 'Wales', 'county'),
('CARMARTHENSHIRE', 'Wales', 'county'),
('DENBIGH', 'Wales', 'county'),
('DENBIGHSHIRE', 'Wales', 'county'),
('FLINT', 'Wales', 'county'),
('FLINTSHIRE', 'Wales', 'county'),
('GLAMORGAN', 'Wales', 'county'),
('GLAMORGANSHIRE', 'Wales', 'county'),
('MERIONETH', 'Wales', 'county'),
('MERIONETHSHIRE', 'Wales', 'county'),
('MONMOUTH', 'Wales', 'county'),
('MONMOUTHSHIRE', 'Wales', 'county'),
('MONTGOMERY', 'Wales', 'county'),
('MONTGOMERYSHIRE', 'Wales', 'county'),
('PEMBROKE', 'Wales', 'county'),
('PEMBROKESHIRE', 'Wales', 'county'),
('RADNOR', 'Wales', 'county'),
('RADNORSHIRE', 'Wales', 'county');

-- Wales cities
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('CARDIFF', 'Wales', 'city'),
('SWANSEA', 'Wales', 'city'),
('NEWPORT', 'Wales', 'city'),
('MERTHYR TYDFIL', 'Wales', 'city'),
('WREXHAM', 'Wales', 'city'),
('BARRY', 'Wales', 'city'),
('NEATH', 'Wales', 'city'),
('LLANELLI', 'Wales', 'city'),
('PONTYPRIDD', 'Wales', 'city'),
('RHONDDA', 'Wales', 'city'),
('BRIDGEND', 'Wales', 'city'),
('ABERDARE', 'Wales', 'city'),
('CAERPHILLY', 'Wales', 'city'),
('PONTYPOOL', 'Wales', 'city'),
('PORT TALBOT', 'Wales', 'city'),
('TONYPANDY', 'Wales', 'city'),
('ABERTILLERY', 'Wales', 'city'),
('EBBW VALE', 'Wales', 'city'),
('TREDEGAR', 'Wales', 'city'),
('MAESTEG', 'Wales', 'city'),
('BANGOR', 'Wales', 'city'),
('LLANDUDNO', 'Wales', 'city'),
('COLWYN BAY', 'Wales', 'city'),
('RHYL', 'Wales', 'city'),
('CARMARTHEN', 'Wales', 'city'),
('PEMBROKE', 'Wales', 'city');

-- Ireland counties
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('ANTRIM', 'Ireland', 'county'),
('ARMAGH', 'Ireland', 'county'),
('CARLOW', 'Ireland', 'county'),
('CAVAN', 'Ireland', 'county'),
('CLARE', 'Ireland', 'county'),
('CORK', 'Ireland', 'county'),
('DERRY', 'Ireland', 'county'),
('DONEGAL', 'Ireland', 'county'),
('DOWN', 'Ireland', 'county'),
('DUBLIN', 'Ireland', 'county'),
('FERMANAGH', 'Ireland', 'county'),
('GALWAY', 'Ireland', 'county'),
('KERRY', 'Ireland', 'county'),
('KILDARE', 'Ireland', 'county'),
('KILKENNY', 'Ireland', 'county'),
('KING''S CO.', 'Ireland', 'county'),
('LAOIS', 'Ireland', 'county'),
('LEITRIM', 'Ireland', 'county'),
('LIMERICK', 'Ireland', 'county'),
('LONDONDERRY', 'Ireland', 'county'),
('LONGFORD', 'Ireland', 'county'),
('LOUTH', 'Ireland', 'county'),
('MAYO', 'Ireland', 'county'),
('MEATH', 'Ireland', 'county'),
('MONAGHAN', 'Ireland', 'county'),
('OFFALY', 'Ireland', 'county'),
('QUEEN''S CO.', 'Ireland', 'county'),
('ROSCOMMON', 'Ireland', 'county'),
('SLIGO', 'Ireland', 'county'),
('TIPPERARY', 'Ireland', 'county'),
('TYRONE', 'Ireland', 'county'),
('WATERFORD', 'Ireland', 'county'),
('WESTMEATH', 'Ireland', 'county'),
('WEXFORD', 'Ireland', 'county'),
('WICKLOW', 'Ireland', 'county');

-- Ireland cities
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('DUBLIN', 'Ireland', 'city'),
('BELFAST', 'Ireland', 'city'),
('CORK', 'Ireland', 'city'),
('LIMERICK', 'Ireland', 'city'),
('GALWAY', 'Ireland', 'city'),
('WATERFORD', 'Ireland', 'city'),
('DERRY', 'Ireland', 'city'),
('LONDONDERRY', 'Ireland', 'city'),
('NEWRY', 'Ireland', 'city'),
('LISBURN', 'Ireland', 'city'),
('KILKENNY', 'Ireland', 'city'),
('DUNDALK', 'Ireland', 'city'),
('DROGHEDA', 'Ireland', 'city'),
('SLIGO', 'Ireland', 'city'),
('WEXFORD', 'Ireland', 'city'),
('ATHLONE', 'Ireland', 'city'),
('TRALEE', 'Ireland', 'city'),
('ENNIS', 'Ireland', 'city'),
('CLONMEL', 'Ireland', 'city'),
('TIPPERARY', 'Ireland', 'city'),
('BALLYMENA', 'Ireland', 'city'),
('BANGOR', 'Ireland', 'city'),
('LURGAN', 'Ireland', 'city'),
('PORTADOWN', 'Ireland', 'city'),
('ARMAGH', 'Ireland', 'city'),
('OMAGH', 'Ireland', 'city'),
('ENNISKILLEN', 'Ireland', 'city'),
('CARRICKFERGUS', 'Ireland', 'city');

-- England counties
INSERT OR IGNORE INTO ref_region_places (place_name, country, type) VALUES
('BEDS', 'England', 'county'),
('BEDFORDSHIRE', 'England', 'county'),
('BERKS', 'England', 'county'),
('BERKSHIRE', 'England', 'county'),
('BUCKS', 'England', 'county'),
('BUCKINGHAMSHIRE', 'England', 'county'),
('CAMBS', 'England', 'county'),
('CAMBRIDGESHIRE', 'England', 'county'),
('CHESHIRE', 'England', 'county'),
('CORNWALL', 'England', 'county'),
('CUMBERLAND', 'England', 'county'),
('DERBYSHIRE', 'England', 'county'),
('DERBY', 'England', 'county'),
('DEVON', 'England', 'county'),
('DEVONSHIRE', 'England', 'county'),
('DORSET', 'England', 'county'),
('DORSETSHIRE', 'England', 'county'),
('DURHAM', 'England', 'county'),
('CO. DURHAM', 'England', 'county'),
('ESSEX', 'England', 'county'),
('GLOUCESTERSHIRE', 'England', 'county'),
('GLOS', 'England', 'county'),
('HAMPSHIRE', 'England', 'county'),
('HANTS', 'England', 'county'),
('HEREFORDSHIRE', 'England', 'county'),
('HERTFORDSHIRE', 'England', 'county'),
('HERTS', 'England', 'county'),
('HUNTINGDONSHIRE', 'England', 'county'),
('HUNTS', 'England', 'county'),
('KENT', 'England', 'county'),
('LANCASHIRE', 'England', 'county'),
('LANCS', 'England', 'county'),
('LEICESTERSHIRE', 'England', 'county'),
('LEICS', 'England', 'county'),
('LINCOLNSHIRE', 'England', 'county'),
('LINCS', 'England', 'county'),
('LONDON', 'England', 'county'),
('MIDDX', 'England', 'county'),
('MIDDLESEX', 'England', 'county'),
('NORFOLK', 'England', 'county'),
('NORTHAMPTONSHIRE', 'England', 'county'),
('NORTHANTS', 'England', 'county'),
('NORTHUMBERLAND', 'England', 'county'),
('NOTTINGHAMSHIRE', 'England', 'county'),
('NOTTS', 'England', 'county'),
('OXFORDSHIRE', 'England', 'county'),
('OXON', 'England', 'county'),
('RUTLAND', 'England', 'county'),
('SHROPSHIRE', 'England', 'county'),
('SALOP', 'England', 'county'),
('SOMERSET', 'England', 'county'),
('STAFFORDSHIRE', 'England', 'county'),
('STAFFS', 'England', 'county'),
('SUFFOLK', 'England', 'county'),
('SURREY', 'England', 'county'),
('SUSSEX', 'England', 'county'),
('WARWICKSHIRE', 'England', 'county'),
('WARWICKS', 'England', 'county'),
('WESTMORLAND', 'England', 'county'),
('WILTSHIRE', 'England', 'county'),
('WILTS', 'England', 'county'),
('WORCESTERSHIRE', 'England', 'county'),
('WORCS', 'England', 'county'),
('YORKSHIRE', 'England', 'county'),
('YORKS', 'England', 'county'),
('E. YORKS', 'England', 'county'),
('N. YORKS', 'England', 'county'),
('W. YORKS', 'England', 'county'),
('N.R. YORKS', 'England', 'county'),
('W.R. YORKS', 'England', 'county'),
('E.R. YORKS', 'England', 'county');

-- ============================================================
-- Place Keywords (overseas/europe indicators for classification)
-- ============================================================
CREATE TABLE IF NOT EXISTS ref_place_keywords (
    keyword TEXT PRIMARY KEY,
    region  TEXT NOT NULL
);

INSERT OR IGNORE INTO ref_place_keywords (keyword, region) VALUES
('INDIA', 'Overseas'),
('CANADA', 'Overseas'),
('AUSTRALIA', 'Overseas'),
('NEW ZEALAND', 'Overseas'),
('SOUTH AFRICA', 'Overseas'),
('CEYLON', 'Overseas'),
('JAMAICA', 'Overseas'),
('BERMUDA', 'Overseas'),
('MALTA', 'Overseas'),
('GIBRALTAR', 'Overseas'),
('GUERNSEY', 'Overseas'),
('JERSEY', 'Overseas'),
('NATAL', 'Overseas'),
('TRANSVAAL', 'Overseas'),
('CAPE', 'Overseas'),
('RHODESIA', 'Overseas'),
('HONG KONG', 'Overseas'),
('SINGAPORE', 'Overseas'),
('BURMA', 'Overseas'),
('EGYPT', 'Overseas'),
('WEST INDIES', 'Overseas'),
('BARBADOS', 'Overseas'),
('TRINIDAD', 'Overseas'),
('BRITISH', 'Overseas'),
('NEWFOUNDLAND', 'Overseas'),
('TASMANIA', 'Overseas'),
('QUEENSLAND', 'Overseas'),
('VICTORIA', 'Overseas'),
('BENGAL', 'Overseas'),
('BOMBAY', 'Overseas'),
('MADRAS', 'Overseas'),
('CALCUTTA', 'Overseas'),
('PUNJAB', 'Overseas'),
('FRANCE', 'Overseas'),
('GERMANY', 'Overseas'),
('BELGIUM', 'Overseas'),
('HOLLAND', 'Overseas'),
('NETHERLANDS', 'Overseas'),
('ITALY', 'Overseas'),
('SPAIN', 'Overseas'),
('PORTUGAL', 'Overseas'),
('RUSSIA', 'Overseas'),
('POLAND', 'Overseas'),
('DENMARK', 'Overseas'),
('SWEDEN', 'Overseas'),
('NORWAY', 'Overseas'),
('SWITZERLAND', 'Overseas'),
('AUSTRIA', 'Overseas');
